CREATE DATABASE IF NOT EXISTS BD_BIBLIOTECA;
USE BD_BIBLIOTECA;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    BIO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    EDITORA VARCHAR(255) NOT NULL,
    FK_AUTOR_CPF VARCHAR(14),
    FK_LEITOR_CPF VARCHAR(14),
    FOREIGN KEY (FK_AUTOR_CPF) REFERENCES AUTOR(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_LEITOR_CPF) REFERENCES LEITOR(CPF) ON DELETE CASCADE
);