CREATE DATABASE IF NOT EXISTS ESTOQUE_SUPERMERCADAO;
USE ESTOQUE_SUPERMERCADAO;

CREATE TABLE IF NOT EXISTS CATEGORIAS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    QTD_PRODUTO INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(14) PRIMARY KEY,
    QTD_CLIENTE INTEGER,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ESTOQUE INTEGER,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VALIDADE INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    PRECO INTEGER NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FK_CATEGORIAS_ID INTEGER,
    FOREIGN KEY (FK_CATEGORIAS_ID) REFERENCES CATEGORIAS(ID)
);

CREATE TABLE IF NOT EXISTS CLIENTE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_PRODUTO_ID INTEGER,
    FK_FORNECEDOR_CNPJ VARCHAR(14),
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(ID),
    FOREIGN KEY (FK_FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ) ON DELETE CASCADE 
);