CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE, 
    USU_AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO", "CASADO", "DIVORCIADO", "VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL", "MÉDIO", "SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY(USU_CODIGO)
);
CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(500) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY(ENQ_CODIGO),
    FK_USU_CODIGO INTEGER NOT NULL,
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO (USU_CODIGO) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    PRIMARY KEY(URE_CODIGO),
    FK_USU_CODIGO INTEGER NOT NULL,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    FOREIGN KEY(FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY(FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    PRIMARY KEY (PER_CODIGO),
    FK_ENQ_CODIGO INTEGER NOT NULL,
    FOREIGN KEY(FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    PRIMARY KEY (RES_CODIGO),
    FK_PER_CODIGO INTEGER NOT NULL,
    FOREIGN KEY(FK_PER_CODIGO) REFERENCES PERGUNTAS(PER_CODIGO) ON DELETE CASCADE
);
-- INSERIR USUARIO
INSERT INTO USUARIO(USU_DATA_CADASTRO,  USU_LOGIN,  USU_AREA_ATUACAO,  USU_PROFISSAO,  USU_DATANASC,  USU_ESTADO_CIVIL, USU_ESTADO,  USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUE ("2025-10-05", "duda_login","professor","professora","2009-01-03","solteiro","SP","superior","duda@email","123456","duda");
INSERT INTO USUARIO(USU_DATA_CADASTRO,  USU_LOGIN,  USU_AREA_ATUACAO,  USU_PROFISSAO,  USU_DATANASC,  USU_ESTADO_CIVIL, USU_ESTADO,  USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUE ("2025-10-06", "maria_login","estudante","estudante","2009-01-04","solteiro","MG","médio","maria@email","6789101112","maria");
INSERT INTO USUARIO(USU_DATA_CADASTRO,  USU_LOGIN,  USU_AREA_ATUACAO,  USU_PROFISSAO,  USU_DATANASC,  USU_ESTADO_CIVIL, USU_ESTADO,  USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUE ("2025-10-07", "eduarda_login","caseiro","caseito","2009-01-05","casado","SC","superior","eduarda@email","1314151617","eduarda");
SELECT * FROM USUARIO;

-- INSERIR ENQUETE
INSERT INTO ENQUETE(ENQ_DATA_FINAL,  ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUE ("2025-12-09","");

-- INSERIR URE
INSERT INTO USUARIO_RESPONDE_ENQUETE()
VALUE ();

-- INSERIR PERGUNTAS
INSERT INTO PERGUNTAS()
VALUE ();

-- INSERT RESPOSTAS
INSERT INTO RESPOSTAS()
VALUE();