CREATE DATABASE IF NOT EXISTS BD_HOTEL;
USE BD_HOTEL;

CREATE TABLE IF NOT EXISTS HOTEL(
	CNPJ VARCHAR(20) PRIMARY KEY,
    DESCRICAO VARCHAR(500) NOT NULL,
    NOME VARCHAR(500) NOT NULL,
    LOCALIZACAO VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL
);

CREATE TABLE IF NOT EXISTS HOSPEDE(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL
);

CREATE TABLE IF NOT EXISTS QUARTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(500) NOT NULL,
    NUMERO INTEGER,
    FK_HOTEL_CNPJ VARCHAR(20),
    FOREIGN KEY (FK_HOTEL_CNPJ) REFERENCES HOTEL(CNPJ) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESERVADO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_QUARTO_ID INTEGER,
    FK_HOSPEDE_CPF VARCHAR(14),
    FOREIGN KEY (FK_QUARTO_ID) REFERENCES QUARTO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_HOSPEDE_CPF) REFERENCES HOSPEDE(CPF) ON DELETE CASCADE
    );