CREATE DATABASE IF NOT EXISTS BD_MEDICO;
USE BD_MEDICO;

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEDICOS(
	CRN VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ESPECIALIZACAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUM INTEGER NOT NULL,
    DATA DATE NOT NULL,
    FK_MEDICO_CRJ VARCHAR(20),
    FK_PACIENTE_CPF VARCHAR(14),
    FOREIGN KEY (FK_MEDICO_CRJ) REFERENCES MEDICO(CRJ) ON DELETE CASCADE,
    FOREIGN KEY (FK_PACIENTE_CPF) REFERENCES PACIENTE(CPF) ON DELETE CASCADE
);