CREATE DATABASE IF NOT EXISTS BD_MUSICA_2ANO;
USE BD_MUSICA_2ANO;

CREATE TABLE IF NOT EXISTS ARTISTAS(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUMM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE,
    AVALIACAO VARCHAR(255),
    QTD_MUSICA INTEGER,
    FK_ARTISTAS_CPF VARCHAR(14),
    FOREIGN KEY (FK_ARTISTAS_CPF) REFERENCES ARTISTAS(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALBUM DATE,
    LETRA VARCHAR(1500) NOT NULL,
    FAIXAETARIA INTEGER, 
    FK_GENERO_ID INTEGER,
    FK_ALBUMM_ID INTEGER,
    FOREIGN KEY (FK_GENERO_ID) REFERENCES GENERO(ID),
    FOREIGN KEY (FK_ALBUMM_ID) REFERENCES ALBUMM(ID)
);