CREATE DATABASE IF NOT EXISTS PROJETO;
USE PROJETO;

CREATE TABLE IF NOT EXISTS PROJETOS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL,
    QTD INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    QTD INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    QTD INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS RESPONSAVEL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_FUNCIONARIOS_CPF VARCHAR(14),
    FK_TAREFA_ID INTEGER,
    FOREIGN KEY (FK_FUNCIONARIOS_CPF) REFERENCES FUNCIONARIOS(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_TAREFA_ID) REFERENCES TAREFA(ID) ON DELETE CASCADE
);