CREATE DATABASE IF NOT EXISTS BD_SUPERMERCADO_2ANO;
USE BD_SUPERMERCADO_2ANO;

CREATE TABLE IF NOT EXISTS SUPERMERCADO(
	CNPJ VARCHAR(20)PRIMARY KEY,
    RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    TELEFONE varchar(15) NOT NULL,
    EMAIL varchar(255) NOT NULL,
    LOGRADOURO varchar(255) NOT NULL,
    NUMERO varchar(5),
    CIDADE varchar(255) NOT NULL,
    ESTADO varchar(2) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
	ID INTEGER auto_increment PRIMARY KEY,
    CODIGO_BARRAS VARCHAR(100) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    PESO varchar(10) NOT NULL,
    QUANTIDADE integer NOT NULL,
    PRECO DOUBLE NOT NULL,
    DATA_VALIDADE DATE 
);

CREATE TABLE IF NOT EXISTS CONSUMIDOR(
	CPF VARCHAR(14) PRIMARY KEY,
    EMAIL varchar(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
	CPF VARCHAR(14) PRIMARY KEY,
    JORNADA_TRABALHO VARCHAR (10) NOT NULL,
    DATA_ADMISSAO DATE NOT NULL,
    BANCO_CONTA VARCHAR(5),
    BANCO_AGENCIA VARCHAR(5),
    CARTEIRA_TRABALHO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FK_SUPERMERCADO_CNPJ VARCHAR(20) NOT NULL,
    FOREIGN KEY (FK_SUPERMERCADO_CNPJ) REFERENCES SUPERMERCADO(CNPJ)
);

CREATE TABLE IF NOT EXISTS SUPERMERCADO_PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_SUPERMERCADO_CNPJ VARCHAR(20),
    FK_PRODUTOS_ID INTEGER,
    FOREIGN KEY (FK_SUPERMERCADO_CNPJ) REFERENCES SUPERMERCADO(CNPJ),
    FOREIGN KEY (FK_PRODUTOS_ID) REFERENCES PRODUTOS(ID)
);

CREATE TABLE IF NOT EXISTS COMPRA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CONSUMIDOR_CPF VARCHAR(14),
    FK_PRODUTOS_ID INTEGER,
    FOREIGN KEY (FK_CONSUMIDOR_CPF) REFERENCES CONSUMIDOR(CPF),
    FOREIGN KEY (FK_PRODUTOS_ID) REFERENCES PRODUTOS(ID)
);

-- ALTERAR TABELA CONSUMIDOR, ADICIONAR DATA_NASCIMENTO
ALTER TABLE CONSUMIDOR 
ADD COLUMN DATA_NASCIMENTO DATE NOT NULL;

-- ALTERAR TABELA SUPERMERCADO, MUDAR COLUNA TELEFONE
ALTER TABLE SUPERMERCADO
CHANGE COLUMN TELEFONE TELEFONE_SUPERMERCADO VARCHAR(15);

-- ALTERA TABELA SUPERMERCADO, MODIFICAR COLUNA LOGRODOURO
ALTER TABLE SUPERMERCADO
MODIFY COLUMN LOGRADOURO VARCHAR(500);

-- ALTERAR TABELA CONSUMIDOR, APAGAR A COLUNA EMAIL
ALTER TABLE CONSUMIDOR
DROP COLUMN EMAIL;

-- APAGAR TABELA FUNCIONARIO
DROP TABLE FUNCIONARIOS;

-- APAGAR O BANCO DE DADOS
DROP DATABASE BD_SUPERMERCADO_2ANO;