CREATE DATABASE IF NOT EXISTS VOO;
USE VOO;

CREATE TABLE IF NOT EXISTS VOAR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_VOAR DATE,
    DESCRICAO VARCHAR(500) NOT NULL,
    COMPANHIA VARCHAR(100) NOT NULL,
    QTD_PASSAGEIROS VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PASSAPORTE VARCHAR(25) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(500) NOT NULL,
    NUMERO INTEGER,
    VALOR DOUBLE NOT NULL,
    FK_VOAR_ID INTEGER,
    FK_PASSAGEIROS_CPF VARCHAR(14),
    FOREIGN KEY (FK_VOAR_ID) REFERENCES VOAR(ID),
    FOREIGN KEY (FK_PASSAGEIROS_CPF) REFERENCES PASSAGEIROS(CPF)
);