CREATE DATABASE IF NOT EXISTS VIDEO;
USE VIDEO;

CREATE TABLE IF NOT EXISTS CATEGORFIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    IDADE INTEGER NOT NULL,
    DESCRICAO VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(500) NOT NULL,
    TEMPO VARCHAR(1000) NOT NULL,
    FK_CATEGORFIA_ID INTEGER,
    FOREIGN KEY (FK_CATEGORFIA_ID) REFERENCES CATEGORFIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VISUALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    INTERACAO VARCHAR(500),
    FK_VIDEO_ID INTEGER,
    FOREIGN KEY (FK_VIDEO_ID) REFERENCES VIDEO(ID) ON DELETE CASCADE
);